version: 1.0
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    driver-class-name: org.gjt.mm.mysql.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.96.112.159:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: old
    password: 123
